stages:
  transform:
    cmd: python src/preprocessing.py data/california_housing.csv data/california_housing_scaled.csv
    deps:
      - data/california_housing.csv
      - src/preprocessing.py
    outs:
      - data/california_housing_scaled.csv